import React, { useState, useEffect, useCallback } from 'react';
import { 
  X, 
  ChevronLeft, 
  ChevronRight, 
  Play, 
  Pause, 
  Maximize2, 
  RotateCcw, 
  Award, 
  Sparkles, 
  CheckCircle2, 
  Droplets, 
  Cpu, 
  Activity, 
  ShieldCheck, 
  ArrowRight,
  BookOpen,
  Waves,
  Layers,
  Zap,
  Radio,
  FileText
} from 'lucide-react';
import { TabType } from '../types';
import { PipeGuardLogo } from './PipeGuardLogo';

interface TourSlide {
  id: number;
  slideNumber: string;
  category: string;
  title: string;
  subtitle: string;
  theme: 'blue' | 'cyan' | 'indigo' | 'emerald' | 'amber' | 'slate';
  bullets: string[];
  keyMetric: {
    value: string;
    label: string;
    description: string;
  };
  visualType: 'diagram' | 'formula' | 'hardware' | 'workflow' | 'comparison' | 'scada' | 'summary';
}

const TOUR_SLIDES: TourSlide[] = [
  {
    id: 1,
    slideNumber: '01 / 08',
    category: 'PROJECT INTRODUCTION',
    title: 'PIPEGUARD — Next-Gen Acoustic Leak Detection',
    subtitle: 'A Low-Cost, Non-Invasive Water Pipeline Vibration Monitoring & Centimeter-Level TDOA Localization System',
    theme: 'cyan',
    bullets: [
      'Developed by Affan Adil under the national INSPIRE-MANAK initiative (DST / NIF India).',
      'Mentored by Arnab Poddar (Sir, PGT Biology) and Mrinmoy Chowhan (Sir, ATL Lab Mentor).',
      'Engineered to tackle the 35–45% Non-Revenue Water (NRW) crisis plaguing municipal distribution grids.',
      'Operates 100% externally with zero pipe cutting, zero drilling, and zero water contamination risk.'
    ],
    keyMetric: {
      value: '₹850',
      label: 'Node Fabrication Cost',
      description: '90%+ cheaper than imported commercial hydrophones ($1,200+)'
    },
    visualType: 'summary'
  },
  {
    id: 2,
    slideNumber: '02 / 08',
    category: 'THE MUNICIPAL CRISIS',
    title: 'The Invisible Water Loss Problem',
    subtitle: 'Underground Micro-Fissures Cause Billions of Liters of Potable Water Waste Every Day',
    theme: 'amber',
    bullets: [
      'Sub-surface pinhole leaks remain undetectable to the human eye for weeks or months.',
      'Traditional detection requires destructive soil excavation or dangerous pipe wall penetration.',
      'Escaping high-pressure water generates distinct turbulent fluid cavitation and structural boundary waves.',
      'Municipalities lose enormous revenue and face structural road cave-ins and sinkhole hazards.'
    ],
    keyMetric: {
      value: '40%',
      label: 'Municipal Water Lost',
      description: 'Treated clean drinking water wasted before reaching household taps'
    },
    visualType: 'comparison'
  },
  {
    id: 3,
    slideNumber: '03 / 08',
    category: 'CORE SENSING HARDWARE',
    title: 'External Piezoelectric Acoustic Transducers',
    subtitle: 'Direct Pipe-Wall Vibration Capture Using Piezoelectric Crystal Resonators',
    theme: 'blue',
    bullets: [
      'Lead Zirconate Titanate (PZT) piezoceramic discs clamp externally around the pipe circumference.',
      'Acoustic silicone elastomer coupling eliminates air-gap attenuation and mechanical slip.',
      'Captures microscopic elastic boundary waves (1 kHz – 50 kHz) generated by fluid cavitation.',
      'Custom preamplifier stage with low-noise active bandpass filtering strips ambient city traffic noise.'
    ],
    keyMetric: {
      value: '1–50 kHz',
      label: 'Acoustic Bandwidth',
      description: 'Optimized resonant window for turbulent water leak cavitation'
    },
    visualType: 'hardware'
  },
  {
    id: 4,
    slideNumber: '04 / 08',
    category: 'MATHEMATICAL LOCALIZATION',
    title: 'TDOA Cross-Correlation Mathematics',
    subtitle: 'Pinpointing Exact Leak Coordinates via Time Difference of Arrival Across Sensor Pairs',
    theme: 'indigo',
    bullets: [
      'Acoustic leak waves propagate bidirectionally along the pipe wall at sound velocity (V ~ 1,200–1,400 m/s in PVC/GI).',
      'Two adjacent sensor nodes (S₁ and S₂) record timestamped acoustic arrival signals with synchronized microsecond clocks.',
      'Cross-correlation function R_xy(τ) computes the exact time lag (Δt) corresponding to peak signal coherence.',
      'Exact leak coordinate formula: X = (L - V · Δt) / 2 where L is the known distance between sensors.'
    ],
    keyMetric: {
      value: '± 8.4 cm',
      label: 'Localization Accuracy',
      description: 'Centimeter precision eliminating random speculative ground digging'
    },
    visualType: 'formula'
  },
  {
    id: 5,
    slideNumber: '05 / 08',
    category: 'SIGNAL PROCESSING PIPELINE',
    title: 'Multi-Stage Edge Signal Filtering Pipeline',
    subtitle: 'From Microscopic Crystal Voltage to Digital Fault Classification',
    theme: 'emerald',
    bullets: [
      'Stage 1: PZT Disc converts structural pipe wall displacement into proportional millivolt AC signal.',
      'Stage 2: Active Sallen-Key Bandpass Filter & Op-Amp PGA (Programmable Gain) suppress low-frequency motor hum.',
      'Stage 3: 12-Bit High-Speed ADC samples at 100 kSps with circular FIFO buffer.',
      'Stage 4: Edge Microcontroller computes RMS amplitude, Peak-to-Average Power Ratio (PAPR), and Fast Fourier Transform (FFT).'
    ],
    keyMetric: {
      value: '< 1.2 s',
      label: 'Edge Detection Time',
      description: 'Continuous real-time fault detection and burst classification'
    },
    visualType: 'workflow'
  },
  {
    id: 6,
    slideNumber: '06 / 08',
    category: 'EXPERIMENTAL VALIDATION',
    title: 'Lab Test Rig Loop & Calibration Data',
    subtitle: 'Empirical Verification Across PVC, Galvanized Iron (GI), and Mild Steel Pipelines',
    theme: 'cyan',
    bullets: [
      'Tested in closed closed-loop calibration rig with controlled 0.5 mm to 3.0 mm calibrated orifices.',
      'Varying internal pipeline pressures tested from 1.5 bar (gravity feed) up to 4.5 bar (pumped supply).',
      'Demonstrated 96.4% true positive leak detection rate with zero false triggers under simulated ambient tap noise.',
      'Signal attenuation curves mapped: acoustic waves travel up to 50–120 meters per sensor node pair.'
    ],
    keyMetric: {
      value: '96.4%',
      label: 'Empirical Accuracy',
      description: 'Consistent detection in controlled lab test rig trials'
    },
    visualType: 'diagram'
  },
  {
    id: 7,
    slideNumber: '07 / 08',
    category: 'TELEMETRY & SCADA TWIN',
    title: 'Live Digital Twin & SCADA Web Platform',
    subtitle: 'Instant MQTT / ESP-NOW Telemetry Streaming to Municipal Cloud Dashboards',
    theme: 'blue',
    bullets: [
      'Low-power ESP32 IoT node transmits localized telemetry alerts to municipal control centers.',
      'Interactive Digital Twin interface renders real-time multi-channel acoustic waveforms and FFT spectra.',
      'Automated severity classification triggers instant SMS and dashboard alarms when RMS exceeds baseline + 3σ.',
      'Full GIS pipeline mapping plots exact GPS coordinate markers for rapid utility repair dispatch.'
    ],
    keyMetric: {
      value: '100 ms',
      label: 'Telemetry Latency',
      description: 'Instant notification before water pressure drops cause supply failure'
    },
    visualType: 'scada'
  },
  {
    id: 8,
    slideNumber: '08 / 08',
    category: 'SOCIETAL & ECOLOGICAL IMPACT',
    title: 'Inspiring Sustainable Smart Cities',
    subtitle: 'Grassroots Innovation Protecting Community Potable Water Grids',
    theme: 'emerald',
    bullets: [
      'Directly aligns with UN Sustainable Development Goal 6 (Clean Water and Sanitation).',
      'Enables low-income municipal councils and rural water boards to deploy advanced non-invasive leak protection.',
      'Eliminates millions of dollars in disruptive asphalt tear-downs and road traffic congestion.',
      'INSPIRE-MANAK national initiative platform proving youth innovation solving real-world infrastructure challenges.'
    ],
    keyMetric: {
      value: 'SDG 6',
      label: 'Clean Water Goal',
      description: 'High societal impact through scalable open-hardware design'
    },
    visualType: 'summary'
  }
];

interface TourModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectTab: (tab: TabType) => void;
}

export const TourModal: React.FC<TourModalProps> = ({
  isOpen,
  onClose,
  onSelectTab,
}) => {
  const [currentSlideIndex, setCurrentSlideIndex] = useState<number>(0);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);

  const totalSlides = TOUR_SLIDES.length;
  const currentSlide = TOUR_SLIDES[currentSlideIndex];

  // Next / Prev slide handlers
  const handleNext = useCallback(() => {
    setCurrentSlideIndex((prev) => (prev < totalSlides - 1 ? prev + 1 : 0));
  }, [totalSlides]);

  const handlePrev = useCallback(() => {
    setCurrentSlideIndex((prev) => (prev > 0 ? prev - 1 : totalSlides - 1));
  }, [totalSlides]);

  // Handle Autoplay timer
  useEffect(() => {
    if (!isOpen || !isPlaying) return;

    const timer = setInterval(() => {
      handleNext();
    }, 7000); // 7s per slide in 2-minute tour

    return () => clearInterval(timer);
  }, [isOpen, isPlaying, handleNext]);

  // Handle keyboard navigation (Left, Right, Space, ESC)
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'ArrowRight') handleNext();
      if (e.key === 'ArrowLeft') handlePrev();
      if (e.key === ' ') {
        e.preventDefault();
        setIsPlaying((p) => !p);
      }
    };

    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      document.body.style.overflow = 'unset';
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose, handleNext, handlePrev]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-slate-950/85 backdrop-blur-md transition-opacity animate-in fade-in duration-200"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Main Slide Deck Container */}
      <div 
        className="relative w-full max-w-5xl bg-slate-900 text-white rounded-2xl sm:rounded-3xl shadow-2xl border border-slate-700/80 overflow-hidden z-10 flex flex-col max-h-[92vh] animate-in zoom-in-95 duration-200"
        role="dialog"
        aria-modal="true"
        aria-labelledby="tour-slide-title"
      >
        {/* Top Header Bar / Deck Controls */}
        <div className="bg-slate-950/90 px-4 sm:px-6 py-3.5 border-b border-slate-800 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <PipeGuardLogo className="w-6 h-6" />
            <div className="flex items-center gap-2">
              <span className="font-display font-bold text-sm text-slate-100 tracking-tight">
                PIPEGUARD
              </span>
              <span className="text-slate-600">/</span>
              <span className="text-xs font-mono font-semibold text-cyan-400">
                2-Minute Interactive PPT Tour
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Play / Pause Autoplay */}
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors ${
                isPlaying 
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40' 
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
              }`}
              title={isPlaying ? 'Pause 2-minute tour' : 'Play 2-minute tour'}
            >
              {isPlaying ? <Pause className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />}
              <span className="hidden sm:inline">{isPlaying ? 'Autoplay On (7s)' : 'Autoplay'}</span>
            </button>

            {/* Slide Index Badge */}
            <div className="px-3 py-1 rounded-lg bg-slate-800 text-slate-300 border border-slate-700 text-xs font-mono font-bold">
              {currentSlide.slideNumber}
            </div>

            {/* Close Button */}
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors"
              aria-label="Close presentation"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Progress Bar */}
        <div className="w-full bg-slate-800 h-1 flex">
          {TOUR_SLIDES.map((slide, idx) => (
            <button
              key={slide.id}
              onClick={() => setCurrentSlideIndex(idx)}
              className={`h-full flex-1 transition-all duration-300 ${
                idx === currentSlideIndex 
                  ? 'bg-gradient-to-r from-cyan-400 to-blue-500' 
                  : idx < currentSlideIndex 
                    ? 'bg-cyan-700/60' 
                    : 'bg-slate-800 hover:bg-slate-700'
              }`}
              title={`Jump to Slide ${idx + 1}: ${slide.title}`}
            />
          ))}
        </div>

        {/* Slide Canvas Area */}
        <div className="p-6 sm:p-10 flex-1 overflow-y-auto flex flex-col justify-between space-y-6 sm:space-y-8 bg-gradient-to-b from-slate-900 via-slate-900 to-slate-950">
          
          {/* Top Slide Meta: Category & Title */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded-md bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 text-[11px] font-mono font-bold uppercase tracking-wider">
                {currentSlide.category}
              </span>
              <span className="text-[11px] font-mono text-slate-500">
                INSPIRE-MANAK SLIDE PRESENTATION
              </span>
            </div>

            <h2 id="tour-slide-title" className="text-2xl sm:text-3xl lg:text-4xl font-display font-extrabold text-white tracking-tight leading-tight">
              {currentSlide.title}
            </h2>

            <p className="text-sm sm:text-base text-slate-300 font-medium leading-relaxed max-w-3xl">
              {currentSlide.subtitle}
            </p>
          </div>

          {/* Slide Main Content Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
            {/* Left: Key Bullet Points */}
            <div className="lg:col-span-7 space-y-3.5 flex flex-col justify-center">
              {currentSlide.bullets.map((bullet, i) => (
                <div 
                  key={i} 
                  className="p-3.5 sm:p-4 rounded-xl bg-slate-800/60 border border-slate-700/70 hover:border-cyan-500/40 transition-colors flex items-start gap-3.5 group"
                >
                  <div className="w-6 h-6 rounded-lg bg-cyan-500/20 text-cyan-400 flex items-center justify-center shrink-0 mt-0.5 border border-cyan-500/30 font-mono text-xs font-bold group-hover:bg-cyan-500 group-hover:text-slate-950 transition-colors">
                    {i + 1}
                  </div>
                  <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                    {bullet}
                  </p>
                </div>
              ))}
            </div>

            {/* Right: Technical Visual & Key Metric Card */}
            <div className="lg:col-span-5 flex flex-col justify-between space-y-4">
              
              {/* Highlight Metric Card */}
              <div className="p-5 sm:p-6 rounded-2xl bg-gradient-to-br from-slate-800 to-slate-850 border border-slate-700 shadow-lg relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/10 rounded-full blur-2xl pointer-events-none" />
                
                <div className="text-[11px] font-mono font-bold uppercase tracking-wider text-cyan-400 mb-1">
                  {currentSlide.keyMetric.label}
                </div>
                <div className="text-3xl sm:text-4xl font-display font-extrabold text-white tracking-tight">
                  {currentSlide.keyMetric.value}
                </div>
                <div className="text-xs text-slate-400 mt-2 leading-relaxed">
                  {currentSlide.keyMetric.description}
                </div>
              </div>

              {/* Dynamic Technical Visual Component */}
              <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 flex-1 flex flex-col justify-center items-center text-center space-y-3 relative">
                {currentSlide.visualType === 'formula' && (
                  <div className="space-y-3 w-full">
                    <div className="text-[10px] font-mono text-indigo-400 font-bold uppercase tracking-wider">
                      ACOUSTIC TDOA GOVERNING FORMULA
                    </div>
                    <div className="p-3 bg-slate-900 rounded-xl border border-indigo-500/30 text-indigo-300 font-mono text-base sm:text-lg font-bold">
                      X = (L - V × Δt) / 2
                    </div>
                    <div className="text-[11px] font-mono text-slate-400">
                      L = 20.0 m | V = 1350 m/s | Δt = Recorded Cross-Correlation Lag
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'hardware' && (
                  <div className="space-y-2.5 w-full">
                    <div className="text-[10px] font-mono text-blue-400 font-bold uppercase tracking-wider">
                      PIEZOELECTRIC CLAMP ASSEMBLY
                    </div>
                    <div className="flex items-center justify-center gap-2 text-xs font-mono text-slate-300">
                      <span className="px-2 py-1 bg-slate-900 rounded border border-slate-700">PZT-5H Disc</span>
                      <span>→</span>
                      <span className="px-2 py-1 bg-slate-900 rounded border border-slate-700">Silicone Gel</span>
                      <span>→</span>
                      <span className="px-2 py-1 bg-slate-900 rounded border border-slate-700">Pipe Wall</span>
                    </div>
                    <div className="text-[11px] font-mono text-slate-400">
                      Non-invasive mechanical acoustic transmission
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'workflow' && (
                  <div className="space-y-2 w-full text-xs font-mono">
                    <div className="text-[10px] font-mono text-emerald-400 font-bold uppercase tracking-wider">
                      4-STAGE EDGE PIPELINE
                    </div>
                    <div className="grid grid-cols-2 gap-2 text-[11px]">
                      <div className="p-2 rounded bg-slate-900 border border-slate-800 text-slate-300">1. PZT Transduction</div>
                      <div className="p-2 rounded bg-slate-900 border border-slate-800 text-slate-300">2. Active Filter</div>
                      <div className="p-2 rounded bg-slate-900 border border-slate-800 text-slate-300">3. 100 kSps ADC</div>
                      <div className="p-2 rounded bg-slate-900 border border-slate-800 text-slate-300">4. Edge FFT/TDOA</div>
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'comparison' && (
                  <div className="space-y-2 w-full text-xs font-mono text-left">
                    <div className="flex justify-between items-center py-1 border-b border-slate-800 text-slate-400">
                      <span>Traditional Excavation</span>
                      <span className="text-red-400 font-bold">Destructive / ₹50k+</span>
                    </div>
                    <div className="flex justify-between items-center py-1 text-cyan-300 font-bold">
                      <span>PipeGuard External Clamping</span>
                      <span className="text-emerald-400">Non-Invasive / ₹850</span>
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'scada' && (
                  <div className="space-y-2 w-full text-xs font-mono">
                    <div className="flex items-center justify-between text-slate-400">
                      <span>MQTT Stream</span>
                      <span className="text-emerald-400 font-bold">Connected (100 Hz)</span>
                    </div>
                    <div className="w-full bg-slate-900 h-2 rounded-full overflow-hidden">
                      <div className="bg-cyan-500 h-full w-4/5 animate-pulse" />
                    </div>
                    <div className="text-[11px] text-slate-400">
                      Live Telemetry streaming to Municipal SCADA
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'diagram' && (
                  <div className="space-y-2 w-full text-xs font-mono">
                    <div className="text-cyan-300 font-bold">Closed-Loop Lab Test Rig</div>
                    <div className="text-[11px] text-slate-400">
                      Tested on PVC &amp; Galvanized Iron pipes with 1.5 – 4.5 bar operating pressure
                    </div>
                  </div>
                )}

                {currentSlide.visualType === 'summary' && (
                  <div className="space-y-2 w-full text-center">
                    <Award className="w-8 h-8 text-amber-400 mx-auto" />
                    <div className="text-xs font-mono text-slate-300 font-semibold">
                      INSPIRE-MANAK National Science Innovation
                    </div>
                    <div className="text-[11px] font-mono text-slate-500">
                      Lead Innovator: Affan Adil
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Slide Deck Navigation Bar */}
        <div className="bg-slate-950 px-4 sm:px-8 py-4 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-3">
          {/* Slide Indicator Dots */}
          <div className="flex items-center gap-1.5">
            {TOUR_SLIDES.map((_, idx) => (
              <button
                key={idx}
                onClick={() => setCurrentSlideIndex(idx)}
                className={`h-2 rounded-full transition-all ${
                  idx === currentSlideIndex 
                    ? 'w-6 bg-cyan-400' 
                    : 'w-2 bg-slate-700 hover:bg-slate-500'
                }`}
                aria-label={`Go to slide ${idx + 1}`}
              />
            ))}
          </div>

          {/* Prev / Next & Explore Actions */}
          <div className="flex items-center gap-2 sm:gap-3 w-full sm:w-auto justify-between sm:justify-end">
            <button
              onClick={handlePrev}
              className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white text-xs font-mono font-semibold transition-colors flex items-center gap-1.5 border border-slate-700"
            >
              <ChevronLeft className="w-4 h-4" />
              <span>Previous</span>
            </button>

            <button
              onClick={handleNext}
              className="px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-mono font-bold transition-all flex items-center gap-1.5 shadow-md hover:shadow-cyan-500/20"
            >
              <span>{currentSlideIndex === totalSlides - 1 ? 'Start Over' : 'Next Slide'}</span>
              <ChevronRight className="w-4 h-4" />
            </button>

            <button
              onClick={() => {
                onClose();
                onSelectTab('dashboard');
              }}
              className="hidden sm:inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-300 border border-cyan-500/30 text-xs font-mono font-semibold transition-colors ml-2"
            >
              <span>Open Dashboard</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
